client/urls.py
from django.urls import path

from .import views

app_name = 'clients'

clients:list

urlpatterns = [
path('', views.clients_list, name='list'),
path('<int:pk>/', views.clients_detail, name='detail'),
path('export/', views.clients_export, name="export"),
path('<int:pk>/delete/', views.clients_delete, name='delete'),
path('<int:pk>/edit/', views.clients_edit, name='edit'),
path('<int:pk>/add-comment/', views.clients_detail, name='add_comment'),
path('<int:pk>/add-file/', views.clients_add_file, name='add_file'),
path('add/', views.clients_add, name="add")
]

easeCRM/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from userprofile.forms import LoginForm
from core.views import index, about
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('', index, name="index"),
    path('dashboard/clients/', include('client.urls')),
    path('about/', about, name="about"),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name="login"),
    path('log-out/', auth_views.LogoutView.as_view(), name="logout"),
    ]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

lead/urls.py
from django.urls import path
from . import views

app_name="leads"
urlpatterns= [
    path('', views.LeadListView.as_view(), name="list"),
    path('<int:pk>/', views.LeadDetailView.as_view(), name="detail"),
    path('add-lead/', views.LeadCreateView.as_view(), name="add"),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name="delete" ),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name="edit"),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(),name="add_comment"),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name="add_file"),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name="convert"),
    path('export/', views.LeadExportView.as_view(), name="export"),
]

client/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from team.models import Team

class Client(models.Model):

    team = models.ForeignKey(Team, related_name="clients", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name="clients", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta: 
        ordering = ('name', )
        
    def __str__(self):
        return self.name
    
class ClientFile(models.Model):
    team = models.ForeignKey(Team, related_name="client_files", on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name="files", on_delete = models.CASCADE)
    file = models.FileField(upload_to="clientfiles")
    created_by = models.ForeignKey(User, related_name="client_files", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

class Comment(models.Model):
    team = models.ForeignKey(Team, related_name="client_comments", on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name="comments", on_delete = models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name="client_comments", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

client/forms.py
from django import forms
from .models import Client, Comment, ClientFile

class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'email', 'description')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'w-full  mt-4 my-4 py-4 px-6 rounded-xl bg-gray-100'}),
            'email': forms.EmailInput(attrs={'class': 'w-full  mt-4 my-4 py-4 px-6 rounded-xl bg-gray-100'}),
            'description': forms.TextInput(attrs={'class': 'w-full  mt-4 my-4 py-4 px-6 rounded-xl bg-gray-100'}),
        }

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

class AddFileForm(forms.ModelForm):
    class Meta:
        model = ClientFile
        fields = ('file',)

client/views.py
import csv
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Client
from .forms import AddClientForm, AddCommentForm, AddFileForm
from team.models import Team
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

@login_required
def clients_export(request):
    clients = Client.objects.filter(created_by=request.user)
    response = HttpResponse(
        content_type="text/csv",
        headers={'Content-Disposition': "attachment; filename='clients.csv'"},
    )
    writer = csv.writer(response)
    writer.writerow(['Client', 'Description', 'Created At', 'Created By'])
    for client in clients:
        writer.writerow([client.name, client.description, client.created_at, client.created_by])
    return response


@login_required
def clients_list(request):
    clients = Client.objects.filter(created_by=request.user)
    return render(request, 'client/clients_list.html', {
        'clients': clients
    })

@login_required
def clients_detail(request, pk):
    client = get_object_or_404(Client, pk = pk, created_by = request.user)
    if request.method == "POST":
        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = request.user.userprofile.active_team
            comment.created_by = request.user
            comment.client = client
            comment.save()

            return redirect('clients:detail', pk=pk)
        
    else:
        form = AddCommentForm();
    return render(request, 'client/clients_detail.html', {
        'client': client,
        'form': form,
        'fileform': AddFileForm()
    })


@login_required
def clients_add(request):
    team = request.user.userprofile.active_team

    if request.method == "POST":
        form = AddClientForm(request.POST)
        if form.is_valid():
            client = form.save(commit=False)
            client.created_by = request.user
            client.team = request.user.userprofile.active_team
            client.save()

            messages.success(request, "Client has been added.")
            return redirect('clients:list')
    else:
        form = AddClientForm()
    return render(request, 'client/clients_add.html', {
            'form': form,
            'team': team,
        })

@login_required
def clients_edit(request, pk):
    client = get_object_or_404(Client, pk = pk, created_by = request.user)
    if request.method == 'POST':
        form = AddClientForm(request.POST, instance=client)
        if form.is_valid():
            client = form.save()
            messages.success(request, "Client has been updated.")
            return redirect('clients:list')
    else:
        form = AddClientForm(instance=client)
    
    return render(request, 'client/clients_edit.html', {'form': form})

@login_required
def clients_delete(request, pk):
    client = get_object_or_404(Client, pk = pk, created_by = request.user)
    client.delete()
    messages.success(request, "Client has been deleted.")
    return redirect('clients:list')


@login_required
def clients_add_file(request, pk):
    client = get_object_or_404(Client, pk = pk, created_by = request.user)

    if request.method == "POST":
        form = AddFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = form.save(commit=False)
            file.team = request.user.userprofile.active_team
            file.client_id = pk
            file.created_by = request.user
            file.save()

        return redirect("clients:detail", pk=pk)
    return redirect("clients:detail", pk=pk)
    

client/templates/client/clients_add.html
{%extends 'core/base.html'%} {%block title%}Add Client{%endblock%} {%block content%}
<div class="py-6 px-6">
  <h1 class="mb-4 font-bold text-2xl">Add Client</h1>
  {%if team.plan.max_clients > team.clients.all|length%}
  <form method="post" action=".">
    {%csrf_token%} {{form.as_p}}
    <button class="py-4 px-8 bg-blue-500 text-white rounded-xl">Submit</button>
  </form>
  {%else%}
  <p class="mt-6 px-6 py-4 bg-red-500 rounded-xl text-white">
    Your team has reached maximum number of clients. Your owner must upgrade your plan.
  </p>
  {%endif%}
</div>
{%endblock%}

client/templates/client/clients_detail.html
{%extends 'core/base.html'%} {%block title%}Client Details{%endblock%} {%block content%}
<div class="py-6 px-6">
  <h1 class="mb-4 text-lg">{{client.name}}</h1>
  {% if client.description%}
  <p class="font-semibold">Description</p>
  <p class="mb-2">{{client.description}}</p>
  {%endif%}
  <p class="font-semibold">Created At</p>
  <p class="mb-2">{{client.created_at|date:"M-d-Y H:i"}}</p>

  <p class="font-semibold">Modified At</p>
  <p class="mb-6">{{client.modified_at|date:"M-d-Y H:i"}}</p>

  <hr class="my-4" />
  <a class="py-2 px-4 rounded-xl text-white bg-green-500" href="{%url 'clients:edit' client.id %}">Edit</a>
  <a class="py-2 px-4 rounded-xl text-white bg-red-500" href="{%url 'clients:delete' client.id %}">Delete</a>
  <hr class="my-4" />

  <h2 class="text-2xl mb-6">Comments</h2>
  <div class="space-y-4">
    {% for comment in client.comments.all %}
    <div class="bg-gray-100 mb-4 py-6 rounded-xl">
      <p><strong>{{comment.created_by}}</strong>@{{comment.created_at}}</p>
      {{comment.content}}
    </div>
    {%endfor%}
  </div>
  <form action="{% url 'clients:add_comment' client.id %}" method="POST">
    {%csrf_token%} {{form.as_p}}
    <button class="py-2 px-4 rounded-4xl bg-blue-500 text-white">Submit</button>
  </form>
  <hr class="my-4" />

  <h2 class="text-2xl mb-6">Files</h2>

  {% for file in client.files.all %}
  <div class="bg-gray-100 mb-4 py-6 rounded-xl">
    <p><strong>{{file.created_by}}</strong>@{{file.created_at}}</p>
    <a href="{{file.file.url}}">Download</a>
  </div>
  {%endfor%}

  <form action="{% url 'clients:add_file' client.id %}" method="POST" enctype="multipart/form-data">
    {%csrf_token%} {{fileform.as_p}}
    <button class="py-2 px-4 rounded-4xl bg-blue-500 text-white">Submit</button>
  </form>
  <hr class="my-4" />

  <a href="{%url 'clients:list' %}">Back to clients</a>
</div>
{%endblock%}

client/templates/client/clients_edit.html
{%extends 'core/base.html'%} {%block title%}Edit Client{%endblock%} {%block content%}
<div class="py-6 px-6">
  <h1 class="text-lg">Edit Client</h1>
  <form method="post" action=".">
    {%csrf_token%} {{form.as_p}}
    <button class="py-4 px-8 bg-blue-500 text-white rounded-xl">Edit</button>
  </form>
</div>
{%endblock%}

client/templates/client/clients_list.html
{%extends 'core/base.html'%} {%block title%}Clients{%endblock%} {%block content%}
<div class="py-6 px-6">
  <div class="flex justify-between">
    <h1 class="mb-4 text-3xl font-bold">Clients</h1>
    <div>
      <a href="{%url 'clients:add' %}" class="inline-block py-4 px-6 bg-green-500 rounded-xl text-white">Add Client</a>
      <a href="{%url 'clients:export' %}" class="inline-block py-4 px-6 bg-blue-500 rounded-xl text-white"
        >Export Client</a
      >
    </div>
  </div>
  {%if clients%}
  <div class="mt-6 flex justify-between">
    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
  </div>
  {%for client in clients%}
  <div class="flex justify-between">
    <p class="py-2 px-2 w-full {%cycle 'bg-gray-100' '' %}">
      <a href="{%url 'clients:detail' client.id%}"> {{client.name}} </a>
    </p>
  </div>
  {%endfor%} {%else%}
  <p class="px-2">There are no clients in the database yet.</p>
  {%endif%}
</div>
{%endblock%}