easeCRM/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from userprofile.forms import LoginForm
from core.views import index, about
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('', index, name="index"),
    path('dashboard/clients/', include('client.urls')),
    path('about/', about, name="about"),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name="login"),
    path('log-out/', auth_views.LogoutView.as_view(), name="logout"),
    ]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

lead/urls.py
from django.urls import path
from . import views

app_name="leads"
urlpatterns= [
    path('', views.LeadListView.as_view(), name="list"),
    path('<int:pk>/', views.LeadDetailView.as_view(), name="detail"),
    path('add-lead/', views.LeadCreateView.as_view(), name="add"),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name="delete" ),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name="edit"),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(),name="add_comment"),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name="add_file"),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name="convert"),
    path('export/', views.LeadExportView.as_view(), name="export"),
]

lead/models.py
from django.db import models
from django.contrib.auth.models import User
from team.models import Team
# Create your models here.
class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, "New"),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )

    team = models.ForeignKey(Team, related_name="leads", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name="leads", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta: 
        ordering = ('name', )
        
    def __str__(self):
        return self.name
    
class LeadFile(models.Model):
    team = models.ForeignKey(Team, related_name="lead_files", on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name="files", on_delete = models.CASCADE)
    file = models.FileField(upload_to="leadfiles")
    created_by = models.ForeignKey(User, related_name="lead_files", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

class Comment(models.Model):
    team = models.ForeignKey(Team, related_name="lead_comments", on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name="comments", on_delete = models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name="lead_comments", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

lead/forms.py
from django import forms
from .models import Lead, Comment, LeadFile

class LeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'description', 'priority', 'status')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'w-full mt-4 my-4 py-4 px-6 rounded-xl bg-gray-100'}),
            'email': forms.TextInput(attrs={'class': 'w-full mt-4 my-4 py-4 px-6 rounded-xl bg-gray-100'}),
            'description': forms.Textarea(attrs={'class': 'w-full mt-4 my-4 py-4 px-6 rounded-xl bg-gray-100'}),
            'priority': forms.Select(attrs={'class': 'w-full mt-4 my-4 py-4 px-6 rounded-xl bg-gray-100'}),
            'status': forms.Select(attrs={'class': 'w-full mt-4 my-4 py-4 px-6 rounded-xl bg-gray-100'}),
        }

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

class AddFileForm(forms.ModelForm):
    class Meta:
        model = LeadFile
        fields = ('file',)

lead/views.py
import csv
from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView,  DetailView, UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from .models import Lead
from .forms import LeadForm, AddCommentForm, AddFileForm
from team.models import Team
from client.models import Client, Comment as ClientComment

class LeadListView(LoginRequiredMixin, ListView):
     model = Lead

     def get_queryset(self):
          queryset = super(LeadListView, self).get_queryset()
          return queryset.filter(created_by = self.request.user,converted_to_client=False )

class LeadDetailView(LoginRequiredMixin, DetailView):
     model = Lead

     def get_context_data(self, **kwargs):
          context = super().get_context_data(**kwargs);
          context['form'] = AddCommentForm()
          context['fileform'] = AddFileForm()
          return context
     
     def get_queryset(self):
          queryset = super(LeadDetailView, self).get_queryset()
          return queryset.filter(created_by = self.request.user, pk = self.kwargs.get('pk'))


class LeadDeleteView(LoginRequiredMixin, DeleteView):
     model = Lead
     success_url = reverse_lazy('leads:list')

     def get_queryset(self):
          queryset = super(LeadDeleteView, self).get_queryset()
          return queryset.filter(created_by = self.request.user, pk = self.kwargs.get('pk'))

     def get(self, request, *args, **kwargs):
          return self.post(request, *args, **kwargs)

class LeadUpdateView(LoginRequiredMixin, UpdateView):
     model = Lead
     fields = ('name', 'email', 'description', 'priority', 'status')
     success_url = reverse_lazy("leads:list")
 
     def get_context_data(self, **kwargs):
          context = super().get_context_data(**kwargs);
          context['title'] = "Edit Lead"
          return context
     
     def get_queryset(self):
          queryset = super(LeadUpdateView, self).get_queryset()
          return queryset.filter(created_by = self.request.user, pk = self.kwargs.get('pk'))
     

class LeadCreateView(LoginRequiredMixin, CreateView):
    model = Lead
    form_class = LeadForm
    success_url = reverse_lazy("leads:list")

    def get_queryset(self):
        queryset = super(LeadCreateView, self).get_queryset()
        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team = self.request.user.userprofile.active_team
        context['team'] = team
        context['title'] = "Add Lead"
        return context

    def form_valid(self, form):
        team = self.request.user.userprofile.active_team
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.team = team
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())
class AddFileView(LoginRequiredMixin, View):
     def post(self, request, *args, **kwargs):
          pk = kwargs.get('pk')
          form = AddFileForm(request.POST, request.FILES)
          if form.is_valid():
               team = self.request.user.userprofile.active_team
               file = form.save(commit=False)
               file.team = team
               file.lead_id = pk
               file.created_by = request.user
               file.save()
          return redirect('leads:detail', pk=pk)

class LeadExportView(LoginRequiredMixin, View):
     def get(self, request, *args, **kwargs):
          leads = Lead.objects.all().filter(created_by=request.user, converted_to_client=False)
          response = HttpResponse(
          content_type="text/csv",
          headers={'Content-Disposition': "attachment; filename='leads.csv'"},
          )
          writer = csv.writer(response)
          writer.writerow(['Lead', 'Description', 'Created At', 'Created By'])
          for lead in leads:
               writer.writerow([lead.name, lead.description, lead.created_at, lead.created_by])
          return response

class AddCommentView(LoginRequiredMixin, View):
     def post(self, request, *args, **kwargs):
          pk = kwargs.get('pk')
          form = AddCommentForm(request.POST)
          if form.is_valid():
               team = self.request.user.userprofile.active_team
               comment = form.save(commit=False)
               comment.team = team
               comment.created_by = request.user
               comment.lead_id = pk
               comment.save()
          return redirect('leads:detail', pk= pk)
     
class ConvertToClientView(LoginRequiredMixin, View):
     def get(self, request, *args, **kwargs):
          lead = get_object_or_404(Lead, created_by=request.user, pk = self.kwargs.get('pk'))
          team = request.user.userprofile.active_team
          client = Client.objects.create(
          name=lead.name,
          email = lead.email,
          description = lead.description,
          created_by = request.user,
          team = team
          )
          lead.converted_to_client = True
          lead.save()

          # Convert lead comments to converted client comments
          comments = lead.comments.all()
          for comment in comments:
               ClientComment.objects.create(
                    content=comment.content,
                    client = client,
                    created_by = comment.created_by,
                    team = team,
               )
          messages.success(request, 'The lead was converted to a client.')
          return redirect('leads:list')

# @login_required
# def leads_list(request):
#      leads = Lead.objects.filter(converted_to_client = False,created_by = request.user)
#      return render(request, 'lead/leads_list.html', {
#          'leads': leads
#      })


# @login_required
# def leads_detail(request, pk):
#      lead = get_object_or_404(Lead, created_by = request.user, pk = pk)
#     #  lead = Lead.objects.filter(created_by=request.user).get(pk=pk)
#      return render(request, 'lead/leads_detail.html', {
#           'lead': lead
#      })


# @login_required
# def leads_edit(request, pk):
#      lead = get_object_or_404(Lead, created_by=request.user, pk = pk)
#      if request.method == "POST":
#           form = AddLeadForm(request.POST, instance=lead)
#           if form.is_valid():
#                form.save()

#           messages.success(request, 'The changes were saved.')
#           return redirect('leads:list')
#      else:
#           form = AddLeadForm(instance=lead)
#           return render(request, 'lead/leads_edit.html', {
#                'form': form
#           })

# @login_required
# def leads_delete(request, pk):
#      lead = get_object_or_404(Lead, created_by=request.user, pk = pk)
#      lead.delete()
#      messages.success(request, 'The lead was deleted.')
#      return redirect('leads:list')

# @login_required
# def add_lead(request):
#     team = Team.objects.filter(created_by=request.user)[0]
#     if request.method == 'POST':
#         form  = AddLeadForm(request.POST)
#         if form.is_valid():
#                 team = Team.objects.filter(created_by=request.user)[0]
#                 lead = form.save(commit = False)
#                 lead.created_by = request.user
#                 lead.team = team
#                 lead.save()
#                 messages.success(request, 'The lead was created.')
#                 return redirect('leads:list')
#     else:
#         form = AddLeadForm()
#     return render(request, 'lead/add_lead.html', {
#         'form': form,
#         'team': team
#     })

# @login_required
# def convert_to_client(request, pk):
#      lead = get_object_or_404(Lead, created_by=request.user, pk = pk)
#      team = Team.objects.filter(created_by=request.user)[0]
#      client = Client.objects.create(
#           name=lead.name,
#           email = lead.email,
#           description = lead.description,
#           created_by = request.user,
#           team = team
#      )
#      lead.converted_to_client = True
#      lead.save()
#      messages.success(request, 'The lead was converted to a client.')
#      return redirect('leads:list')

lead/templates/lead/lead_detail.html
{%extends 'core/base.html'%} {%block title%}Leads{%endblock%} {%block content%}
<div class="py-6 px-6">
  <h1 class="mb-4 font-bold text-3xl">{{lead.name}}</h1>
  {% if lead.description%}
  <p class="font-semibold">Description</p>
  <p class="mb-2">{{lead.description}}</p>
  {%endif%}
  <p class="font-semibold">Priority</p>
  <p class="mb-2">{{lead.get_priority_display}}</p>
  <p class="font-semibold">Status</p>
  <p class="mb-2">{{lead.get_status_display}}</p>

  <p class="font-semibold">Created At</p>
  <p class="mb-2">{{lead.created_at|date:"M-d-Y H:i"}}</p>

  <p class="font-semibold">Modified At</p>
  <p class="mb-6">{{lead.modified_at|date:"M-d-Y H:i"}}</p>

  <hr class="my-4" />
  <form id="lead_delete_form" method="post" action="{%url 'leads:delete' lead.id%}">{% csrf_token %}</form>

  <a class="py-2 px-4 rounded-xl text-white bg-blue-500" href="{%url 'leads:convert' lead.id%}">Convert to client</a>
  <a class="py-2 px-4 rounded-xl text-white bg-green-500" href="{%url 'leads:edit' lead.id%}">Edit</a>
  <a
    class="py-2 px-4 rounded-xl text-white bg-red-500"
    onclick="document.getElementById('lead_delete_form').submit();"
    href="#"
    >Delete</a
  >
  <hr class="my-4" />

  <h2 class="text-2xl mb-6">Comments</h2>
  <div class="space-y-4">
    {% for comment in lead.comments.all %}
    <div class="bg-gray-100 mb-4 py-6 rounded-xl">
      <p><strong>{{comment.created_by}}</strong>@{{comment.created_at}}</p>
      {{comment.content}}
    </div>
    {%endfor%}
  </div>
  <form action="{% url 'leads:add_comment' lead.id %}" method="POST">
    {%csrf_token%} {{form.as_p}}
    <button class="py-2 px-4 rounded-4xl bg-blue-500 text-white">Submit</button>
  </form>
  <hr class="my-4" />

  <h2 class="text-2xl mb-6">Files</h2>

  {% for file in lead.files.all %}
  <div class="bg-gray-100 mb-4 py-6 rounded-xl">
    <p><strong>{{file.created_by}}</strong>@{{file.created_at}}</p>
    <a href="{{file.file.url}}">Download</a>
  </div>
  {%endfor%}

  <form action="{% url 'leads:add_file' lead.id %}" method="POST" enctype="multipart/form-data">
    {%csrf_token%} {{fileform.as_p}}
    <button class="py-2 px-4 rounded-4xl bg-blue-500 text-white">Submit</button>
  </form>
  <hr class="my-4" />
  <a href="{%url 'leads:list' %}">Back to leads</a>
</div>
{%endblock%}

lead/templates/lead/lead_form.html
{%extends 'core/base.html'%} {%block title%}{{title}}{%endblock%} {%block content%}
<div class="py-6 px-6">
  <h1 class="mb-4 font-bold text-2xl">{{title}}</h1>
  {% if team.plan.max_leads > team.leads.count or title == 'Edit Lead'%}
  <form method="post" action=".">
    {%csrf_token%} {{form.as_p}}
    <button class="py-4 px-8 bg-blue-500 text-white rounded-xl">Submit</button>
  </form>
  {%else%}
  <p class="mt-6 px-6 py-4 bg-red-400 rounded-xl text-white">
    You team has reached maximum number of leads. Your owner must upgrade your plan!
  </p>
  {%endif%}
</div>
{%endblock%}

lead/templates/lead/lead_list.html
{%extends 'core/base.html'%} {%block title%}Leads{%endblock%} {%block content%}
<div class="py-6 px-6">
  <div class="flex justify-between">
    <h1 class="mb-4 text-3xl font-bold">Leads</h1>
    <div>
      <a href="{%url 'leads:add'%}" class="inline-block py-4 px-6 bg-green-500 rounded-xl text-white">Add Lead</a>
      <a href="{%url 'leads:export' %}" class="inline-block py-4 px-6 bg-blue-500 rounded-xl text-white"
        >Export Leads</a
      >
    </div>
  </div>

  {%if object_list%}
  <div class="mt-6 flex justify-between">
    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
  </div>
  {%for lead in object_list%}
  <div class="flex justify-between">
    <p class="py-2 px-2 w-full {%cycle 'bg-gray-100' '' %}">
      <a href="{%url 'leads:detail' lead.id%}"> {{lead.name}} </a>
    </p>
    <p class="py-2 px-2 w-full {%cycle 'bg-gray-100' '' %}">{{lead.get_priority_display}}</p>
    <p class="py-2 px-2 w-full {%cycle 'bg-gray-100' '' %}">{{lead.get_status_display}}</p>
  </div>
  {%endfor%} {%else%}
  <p class="px-2">There are no leads in the database yet.</p>
  {%endif%}
</div>
{%endblock%}