client/urls.py
from django.urls import path

from .import views

app_name = 'clients'

clients:list

urlpatterns = [
path('', views.clients_list, name='list'),
path('<int:pk>/', views.clients_detail, name='detail'),
path('export/', views.clients_export, name="export"),
path('<int:pk>/delete/', views.clients_delete, name='delete'),
path('<int:pk>/edit/', views.clients_edit, name='edit'),
path('<int:pk>/add-comment/', views.clients_detail, name='add_comment'),
path('<int:pk>/add-file/', views.clients_add_file, name='add_file'),
path('add/', views.clients_add, name="add")
]

dashboard/urls.py
from django.urls import path

from . import views 

app_name = "dashboard"
urlpatterns = [
    path('', views.dashboard, name="index")
]

easeCRM/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from userprofile.forms import LoginForm
from core.views import index, about
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('', index, name="index"),
    path('dashboard/clients/', include('client.urls')),
    path('about/', about, name="about"),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name="login"),
    path('log-out/', auth_views.LogoutView.as_view(), name="logout"),
    ]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

lead/urls.py
from django.urls import path
from . import views

app_name="leads"
urlpatterns= [
    path('', views.LeadListView.as_view(), name="list"),
    path('<int:pk>/', views.LeadDetailView.as_view(), name="detail"),
    path('add-lead/', views.LeadCreateView.as_view(), name="add"),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name="delete" ),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name="edit"),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(),name="add_comment"),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name="add_file"),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name="convert"),
    path('export/', views.LeadExportView.as_view(), name="export"),
]

dashboard/models.py
from django.db import models

# Create your models here.

lead/models.py
from django.db import models
from django.contrib.auth.models import User
from team.models import Team
# Create your models here.
class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, "New"),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )

    team = models.ForeignKey(Team, related_name="leads", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name="leads", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta: 
        ordering = ('name', )
        
    def __str__(self):
        return self.name
    
class LeadFile(models.Model):
    team = models.ForeignKey(Team, related_name="lead_files", on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name="files", on_delete = models.CASCADE)
    file = models.FileField(upload_to="leadfiles")
    created_by = models.ForeignKey(User, related_name="lead_files", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

class Comment(models.Model):
    team = models.ForeignKey(Team, related_name="lead_comments", on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name="comments", on_delete = models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name="lead_comments", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from lead.models import Lead
from client.models import Client
from team.models import Team
# Create your views here.

@login_required
def dashboard(request):
    team = request.user.userprofile.active_team
    leads = Lead.objects.filter(team=team, converted_to_client=False).order_by('-created_at')[:5]
    clients = Client.objects.filter(team=team).order_by('-created_at')[:5]
    return render(request, 'dashboard/dashboard.html', {
        'leads': leads,
        'clients': clients,
    })

dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %} {% block title %}Dashboard{% endblock %} {% block content %}
<div class="py-6 px-6">
  <!-- Use h-screen to make it full height -->
  <h1 class="text-3xl font-bold mb-6">Dashboard</h1>
  <div class="flex space-x-4 h-full">
    <!-- Use h-full to make child divs full height -->
    <div class="leads bg-gray-100 rounded-xl px-4 py-6 w-1/2 overflow-y-auto">
      <!-- Use overflow-y-auto for scroll if content overflows -->
      <h2 class="text-lg font-bold">Newest Leads</h2>
      {% for lead in leads %}
      <div class="lead mb-2 py-4">
        <div class="flex items-center justify-between">
          <!-- Added flex container for name and button alignment -->
          <h3 class="font-semibold">{{ lead.name }}</h3>
          <a href="{% url 'leads:detail' lead.pk %}" class="text-white bg-blue-800 px-3 py-1 rounded">Details</a>
        </div>
        <p class="text-xs">Status: {{ lead.get_status_display }}</p>
        <p class="text-xs">Priority: {{ lead.get_priority_display }}</p>
      </div>
      {% endfor %}
    </div>
    <div class="clients bg-gray-100 rounded-xl px-4 py-6 w-1/2 overflow-y-auto">
      <h2 class="text-lg font-bold mb-4">Newest Clients</h2>
      {% for client in clients %}
      <div class="client mb-2 py-2">
        <div class="flex items-center justify-between">
          <!-- Added flex container for name and button alignment -->
          <h3 class="font-semibold">{{ client.name }}</h3>
          <a href="{% url 'clients:detail' client.pk %}" class="text-white bg-blue-800 px-3 py-1 rounded">Details</a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}