dashboard/urls.py
from django.urls import path

from . import views 

app_name = "dashboard"
urlpatterns = [
    path('', views.dashboard, name="index")
]

easeCRM/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from userprofile.forms import LoginForm
from core.views import index, about
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('', index, name="index"),
    path('dashboard/clients/', include('client.urls')),
    path('about/', about, name="about"),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name="login"),
    path('log-out/', auth_views.LogoutView.as_view(), name="logout"),
    ]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

lead/urls.py
from django.urls import path
from . import views

app_name="leads"
urlpatterns= [
    path('', views.LeadListView.as_view(), name="list"),
    path('<int:pk>/', views.LeadDetailView.as_view(), name="detail"),
    path('add-lead/', views.LeadCreateView.as_view(), name="add"),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name="delete" ),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name="edit"),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(),name="add_comment"),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name="add_file"),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name="convert"),
    path('export/', views.LeadExportView.as_view(), name="export"),
]

team/urls.py
from django.urls import path

from . import views

app_name = "team"

urlpatterns = [
    path('', views.teams_list, name="list"),
    path('<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/edit/', views.edit_team, name="edit" ),
    path('<int:pk>/activate/', views.teams_activate, name="activate" )
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = "userprofile"

urlpatterns = [
    path('myaccount/', views.myaccount, name="myaccount"),
    path('sign-up/', views.signup, name="signup"),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "core/index.html")

def about(request):
    return render(request, 'core/about.html')

core/templates/core/partials/footer.html
<footer class="py-8 text-center bg-gray-200">
  <p class="text-xs text-gray-700">Copyright (c) 2024 - EaseCRM</p>
</footer>

core/templates/core/partials/nav.html
<nav class="py-4 px-6 flex justify-between bg-blue-500">
  <div class="flex items-center justify-between w-full">
    <a href="{% url 'about' %}" class="py-3 text-3xl font-bold px-6 rounded-xl text-white">EaseCRM</a>
    {%if request.user.is_authenticated%}
    <div class="flex space-x-4">
      <a href="{% url 'team:detail' active_team.id %}" class="py-4 px-6 rounded-xl text-white">{{active_team.name}}</a>
      <a href="{%url 'dashboard:index'%}" class="py-4 px-6 bg-blue-600 rounded-xl text-white">Dashboard</a>
      <a href="{%url 'leads:list'%}" class="py-4 px-6 bg-blue-600 rounded-xl text-white">Leads</a>
      <a href="{%url 'clients:list'%}" class="py-4 px-6 bg-blue-600 rounded-xl text-white">Clients</a>
      <a href="{%url 'userprofile:myaccount'%}" class="py-4 px-6 bg-blue-700 rounded-xl text-white">My account</a>
      {% else %}
      <div>
        <a href="{%url 'login'%}" class="py-4 px-6 bg-blue-600 rounded-xl text-white">Log in</a>
        <a href="{%url 'userprofile:signup'%}" class="py-4 px-6 bg-blue-300 rounded-xl text-white">Sign up</a>
      </div>
      {% endif %}
    </div>
  </div>
</nav>